### ISSUE TITLE
Compilable version

### ISSUE THREAD

**Issue by faisalr** [gjulianm/Ocell#26]
Hello,

I want a compilable version of Ocell, I tried for 1 hour without any success.

Can you send me a working version without sensitive data?

Thanks,
Faisal

**Comment by gjulianm** [comment]
Hi

What is the exact compilation error you're getting? I can't send you a
working version right now.

## 

Guillermo Julián
Twitter http://twitter.com |  Blog http://nuncaalaprimera.com

**Comment by faisalr** [comment]
I am missing a lot of references and project although I found some of them in your repositories. 

I would wait for working version rather than trying to solve the errors even it's going to take you long time.
